# Generated by Django 5.1.6 on 2026-03-24 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='csv_data',
            field=models.FileField(upload_to='data/'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='template',
            field=models.ImageField(upload_to='templates/'),
        ),
    ]
